export const PesticidesData = [
  {
    id: 1,
    Name: "Glyphosite Herbicide combo",
    Description:" 1 Litres pack of 2" ,
    Price: "₹ 349",
    Image: "./Product_images/ph1.png",
    Warranty:"2 Months ",
  },
  {
      id: 2,
      Name: "Sempra Herbicide ",
      Description:"weight 500 gm Halosulphuron Methyl 75 %" ,
      Price: " ₹ 560",
      Image: "./Product_images/ph2.png",
      Warranty:"1 year",
    },
    {
      id: 3,
      Name: "Ronfen Insecticide",
      Description: " 1 Litre Pack highly toxic",
      Price: "₹ 399",
      Image: "./Product_images/ph3.png",
      Warranty:"No warranty",
    },
    {
      id: 4,
      Name: "Glycocin",
      Description: " Herbicide weight 5 Litres",
      Price: "₹ 1299",
      Image: "./Product_images/ph4.png",
      Warranty:"1 year",
    },
    {
      id: 5,
      Name: "Kalichakra",
      Description: " Biological Insecticide Pack of 3",
      Price: "₹ 699",
      Image: "./Product_images/ph5.png",
      Warranty:"No warranty",
    },
    {
      id: 6,
      Name: "Phoskill and Solomon",
      Description: "Insecticides 1 litres each",
      Price: "₹ 499",
      Image: "./Product_images/ph6.png",
      Warranty:"No warranty",
    },
    {
      id: 7,
      Name:"Exponus",
      Description: "Insecticide contains Brofanilide chemical",
      Price: "₹ 387",
      Image: "./Product_images/ph7.png",
      Warranty:"No warranty",
    },
    {
      id: 8,
      Name: "Glybin",
      Description: "Glyphosphate Herbicide contains 41 % concentration",
      Price: "₹ 567",
      Image: "./Product_images/ph8.png",
      Warranty:"1 year ",
    },
  
];

