export const EducationalResourceData= [
  {
    id: "001",
    Name: "Krishi shikshan",
    Description:"writeen By : Dr M.M.Aggrawal Language : Hindi " ,
    Price: 'Rs 240',
    Image: "./Product_images/fe1.png",
    Warranty:"No warranty",
  },
  {
      id: "002",
      Name: "BIO NPK",
      Description: " RATAN GOLD Publication net weight 1 kg language : English",
      Price: "Rs 237",
      Image: "./Product_images/fe2.png",
      Warranty:"6 months",
    },
    {
      id: "003",
      Name: "From the farm to the table ",
      Description: "farm guide for health food from the farms language :English",
      Price: "Rs 149",
      Image: "./Product_images/fe3.png",
      Warranty:"No warranty",
    },
    {
      id: "004",
      Name: "Advances in Extension Education",
      Description: "By Dr.D. K Dangi & Dr. K.S Kadian language : English",
      Price: "Rs 399",
      Image: "./Product_images/fe4.png",
      Warranty:"1 year",
    },
    {
      id: "005",
      Name: "Farm Production",
      Description: "By Dr. Rangalal Mohapatra language: English",
      Price: "Rs 349",
      Image: "./Product_images/fe5.png",
      Warranty:"No warranty",
    },
    {
      id: "006",
      Name: "Ploughing up the farm",
      Description: "Modern technology and the state of world's Farmers language : english",
      Price: "Rs 459",
      Image: "./Product_images/fe6.png",
      Warranty: " 1 year",
    },
    {
      id: "007",
      Name:"Why We Farm",
      Description: " By Elvira Digrit language: english",
      Price: "Rs 299",
      Image: "./Product_images/fe7.png",
      Warranty:"No warranty",
    },
    {
      id: "008",
      Name: "Krishi samanya adhyayan",
      Description: " Language : Hindi",
      Price: "Rs 99",
      Image: "./Product_images/fe8.png",
      Warranty:"No warranty",
    },
    {
      id: "009",
      Name: "URJA",
      Description: "Carrier based consotia available in Both HIndi and English ",
      Price: "Rs 149",
      Image: "./Product_images/fe9.png",
      Warranty:"6 Months",
    },
  
];
