export const EducationalResourceData= [
  {
    id: 14,
    Name: "Krishi shikshan",
    Description:"writeen By : Dr M.M.Aggrawal Language : Hindi " ,
    Rs: 240,
    Image: "./Product_images/fe1.png",
    Warranty:"No warranty",
  },
  {
      id: 15,
      Name: "BIO NPK",
      Description: " RATAN GOLD Publication net weight 1 kg language : English",
      Rs: 237,
      Image: "./Product_images/fe2.png",
      Warranty:"6 months",
    },
    {
      id: 16,
      Name: "From the farm to the table ",
      Description: "farm guide for health food from the farms language :English",
      Rs: 149,
      Image: "./Product_images/fe3.png",
      Warranty:"No warranty",
    },
    {
      id: 17,
      Name: "Advances in Extension Education",
      Description: "By Dr.D. K Dangi & Dr. K.S Kadian language : English",
      Rs: 399,
      Image: "./Product_images/fe4.png",
      Warranty:"1 year",
    },
    {
      id: 18,
      Name: "Farm Production",
      Description: "By Dr. Rangalal Mohapatra language: English",
      Rs: 349,
      Image: "./Product_images/fe5.png",
      Warranty:"No warranty",
    },
    {
      id: 19,
      Name: "Ploughing up the farm",
      Description: "Modern technology and the state of world's Farmers language : english",
      Rs: 459,
      Image: "./Product_images/fe6.png",
      Warranty: " 1 year",
    },
    {
      id: 20,
      Name:"Why We Farm",
      Description: " By Elvira Digrit language: english",
      Rs: 299,
      Image: "./Product_images/fe7.png",
      Warranty:"No warranty",
    },
    {
      id: 21,
      Name: "Krishi samanya adhyayan",
      Description: " Language : Hindi",
      Rs: 99,
      Image: "./Product_images/fe8.png",
      Warranty:"No warranty",
    },
    {
      id: 22,
      Name: "URJA",
      Description: "Carrier based consotia available in Both HIndi and English ",
      Rs: 149,
      Image: "./Product_images/fe9.png",
      Warranty:"6 Months",
    },
  
];
