
export const FarmToolsData = [
  {
    id: 23,
    Name: "Neptune Sprayers",
    Description: " High Quality fibre made color: Orange",
    Rs: "₹ 789",
    Image: "./Product_images/ft1.png",
    Warranty:"No warranty",
  },
  {
      id: 24,
      Name: " Tarpaulin",
      Description: " High Quality fibre made color: Black Highly Durable",
      Rs: "₹ 879",
      Image: "./Product_images/ft2.png",
      Warranty:"2 years",
    },
    {
      id: 25,
      Name: "Brush Cutter",
      Description: " High Quality Durable Color: Red",
      Rs: "₹ 4899",
      Image: "./Product_images/ft3.png",
      Warranty:"3 years ",
    },
    {
      id: 26,
      Name: "Pwer Weeder",
      Description: " Durable color : orange and black strong and easy to hold",
      Rs: "₹ 3299",
      Image: "./Product_images/ft4.png",
      Warranty:"2 years",
    },
    {
      id: 27,
      Name: "Power Weeder",
      Description: " Brand : shrachi  weight: 30 kg easy to hold and made with non rustable material",
      Rs: "₹ 5349",
      Image: "./Product_images/ft5.png",
      Warranty:"2 years",
    },
    {
      id: 28,
      Name: "Eart Euger",
      Description: " Brand : shrachi  weight: 10 kg easy to hold and made with non rustable material",
      Rs: 1299,
      Image: "./Product_images/ft6.png",
      Warranty:"1 year",
    },
    {
      id: 29,
      Name:"Mowers and Trimmers",
      Description: " High Qulaity strong and durable",
      Rs: 3299,
      Image: "./Product_images/ft7.png",
      Warranty:"1 year",
    },
    {
      id: 30,
      Name: "Ploughers",
      Description: " High Quality Made of Non Rustable material color : Red",
      Rs: 2299,
      Image:"./Product_images/ft8.png", 
      Warranty:" 2 years on body and motor",
    },
  
];
