
export const FarmToolsData = [
  {
    id: "001",
    Name: "Neptune Sprayers",
    Description: " High Quality fibre made color: Orange",
    Price: "Rs 789",
    Image: "./Product_images/ft1.png",
    Warranty:"No warranty",
  },
  {
      id: "002",
      Name: " Tarpaulin",
      Description: " High Quality fibre made color: Black Highly Durable",
      Price: "Rs 879",
      Image: "./Product_images/ft2.png",
      Warranty:"2 years",
    },
    {
      id: "003",
      Name: "Brush Cutter",
      Description: " High Quality Durable Color: Red",
      Price: "Rs 4899",
      Image: "./Product_images/ft3.png",
      Warranty:"3 years ",
    },
    {
      id: "004",
      Name: "Pwer Weeder",
      Description: " Durable color : orange and black strong and easy to hold",
      Price: "Rs 3299",
      Image: "./Product_images/ft4.png",
      Warranty:"2 years",
    },
    {
      id: "005",
      Name: "Power Weeder",
      Description: " Brand : shrachi  weight: 30 kg easy to hold and made with non rustable material",
      Price: "Rs 5349",
      Image: "./Product_images/ft5.png",
      Warranty:"2 years",
    },
    {
      id: "006",
      Name: "Eart Euger",
      Description: " Brand : shrachi  weight: 10 kg easy to hold and made with non rustable material",
      Price: "Rs 1299",
      Image: "./Product_images/ft6.png",
      Warranty:"1 year",
    },
    {
      id: "007",
      Name:"Mowers and Trimmers",
      Description: " High Qulaity strong and durable",
      Price: "Rs 3299",
      Image: "./Product_images/ft7.png",
      Warranty:"1 year",
    },
    {
      id: "008",
      Name: "Ploughers",
      Description: " High Quality Made of Non Rustable material color : Red",
      Price: "Rs 2299",
      Image:"./Product_images/ft8.png", 
      Warranty:" 2 years on body and motor",
    },
  
];
