export const FertilizersData = [
    {
      id: 31,
      Name:"Boron Fertilizer" ,
      Description: "weight: 50kg Good Quality 20% boron concentarte" ,
      Price: "₹ 499",
      Image: "./Product_images/f1.png",
      Warranty:"",
    },
    {
        id: 32,
        Name: "Phosphate Fertilizer",
        Description: " Brand : PHOM  weight: 30 kg",
        Price: "₹ 999",
        Image: "./Product_images/f2.png",
        Warranty:"3 months",
      },
      {
        id: 33,
        Name: "Magnesium Sulphate Fertilizer",
        Description: "weight: 20 kg  magnesium: 9.5% sulphur:12 %",
        Price: "₹ 799",
        Image: "./Product_images/f3.png",
        Warranty:"2 Months",
      },
      {
        id: 34,
      Name:"Bio Fertilizer" ,
      Description: "weight: 50kg brand:Calsiphos",
      Price: "₹ 499",
      Image: "./Product_images/f4.png",
      Warranty:"6 Months",
      },
      {
        id: 35,
        Name: "Ammonium Sulphate Fertilizer",
        Description: "Brand:Gacil weight :10 kg",
        Price: "₹ 1299",
        Image: "./Product_images/f5.png",
        Warranty:"No warranty",
      },
      {
        id: 36,
        Name: "Multi Micronutrient Fertilizer",
        Description: "Brand : ProKissan  weight : 20 kg",
        Price: "₹ 1499",
        Image: "./Product_images/f6.png",
        Warranty:"1 Year",
      },
      {
        id: 37,
        Name:" Plant Fertilizer",
        Description: "Brand : Gardeco weight : 10 kg",
        Price: " ₹ 499",
        Image: "./Product_images/f7.png",
        Warranty:"No Warranty",
      },
      {
        id: 38,
        Name: "DAP & MOP ",
        Description: " Good Quality flower and fruit fertilizers weight: 5 kg each",
        Price: "₹ 599",
        Image: "./Product_images/f8.png",
        Warranty:"No Warranty",
      },
    
  ];
