export const SafetyGearsData = [
  {
    id: "001",
    Name: "Full Farm Safety Kit",
    Description:" High Grade Quality contains all necessary equipments" ,
    Price: "Rs 1299",
    Image: "./Products_images/fc1.png",
    Warranty:"1 Year",
  },
  {
      id: "002",
      Name: "Personal Protective Equipment",
      Description: " color : White Highly Durable strechable fit",
      Price: "Rs 1599",
      Image: "./Products_images/fc2.png",
      Warranty:"1 year",
    },
    {
      id: "003",
      Name: "Farm Gloves and Mask",
      Description: " Branded Highly Durable ventilated",
      Price: "Rs 567",
      Image: "./Products_images/fc3.png",
      Warranty:"6 months",
    },
    {
      id: "004",
      Name: "Kisan Kavach ",
      Description: " Former Respiratory, Eye & Hand protection kit",
      Price: "Rs 1199",
      Image: "./Products_images/fc4.png",
      Warranty:" 6 Months",
    },
    {
      id: "005",
      Name: "Promax Farm Mask ",
      Description: "PS 410 SLV color : yellow",
      Price: "Rs 99",
      Image: "./Products_images/fc5.png",
      Warranty:"No warranty",
    },
    {
      id: "006",
      Name: "Farm Boots",
      Description: "Durable High Quality easy fit color :Blue",
      Price: "Rs 349",
      Image: "./Products_images/fc6.png",
      Warranty:"6 Months",
    },
    {
      id: "007",
      Name:"Farm Apron",
      Description: " Protects from harmful chemicals large sized color : yellow",
      Price: "Rs 149",
      Image: "./Products_images/fc7.png",
      Warranty:"No warranty",
    },
    {
      id: "008",
      Name: "KIT PHYTOSANITAIRE",
      Description: "complete farm protection kit protects from harmful rays and chemicals",
      Price: "Rs 679",
      Image: "./Products_images/fc8.png",
      Warranty:"6 months",
    },
  
];
