export const SafetyGearsData = [
  {
    id: 39,
    Name: "Full Farm Safety Kit",
    Description:" High Grade Quality contains all necessary equipments" ,
    Rs: 1299,
    Image: "./Product_images/fc1.png",
    Warranty:"1 Year",
  },
  {
      id: 40,
      Name: "Personal Protective Equipment",
      Description: " color : White Highly Durable strechable fit",
      Rs: 1599,
      Image: "./Product_images/fc2.png",
      Warranty:"1 year",
    },
    {
      id: 41,
      Name: "Farm Gloves and Mask",
      Description: " Branded Highly Durable ventilated",
      Rs: 567,
      Image: "./Product_images/fc3.png",
      Warranty:"6 months",
    },
    {
      id: 42,
      Name: "Kisan Kavach ",
      Description: " Former Respiratory, Eye & Hand protection kit",
      Rs: 1199,
      Image: "./Product_images/fc4.png",
      Warranty:" 6 Months",
    },
    {
      id: 43,
      Name: "Promax Farm Mask ",
      Description: "PS 410 SLV color : yellow",
      Rs: 99,
      Image: "./Product_images/fc5.png",
      Warranty:"No warranty",
    },
    {
      id: 44,
      Name: "Farm Boots",
      Description: "Durable High Quality easy fit color :Blue",
      Rs: 349,
      Image: "./Product_images/fc6.png",
      Warranty:"6 Months",
    },
    {
      id: 45,
      Name:"Farm Apron",
      Description: " Protects from harmful chemicals large sized color : yellow",
      Rs: 149,
      Image: "./Product_images/fc7.png",
      Warranty:"No warranty",
    },
    {
      id: 46,
      Name: "KIT PHYTOSANITAIRE",
      Description: "complete farm protection kit protects from harmful rays and chemicals",
      Rs: 679,
      Image: "./Product_images/fc8.png",
      Warranty:"6 months",
    },
  
];
