export const SeedsData= [
  {
    id: "001",
    Name: " High Quality Hybrid seeds",
    Description: " Pack of 6",
    Price: "Rs 399",
    Image: "./Product_images/se1.png",
    Warranty:"No warranty",
  },
  {
      id: "002",
      Name: "Seminis",
      Description: "High Quality Hybrid Tomato seeds",
      Price: "Rs 249",
      Image: "./Product_images/se2.png",
      Warranty:"1 year from date of manufacture",
    },
    {
      id: "003",
      Name: "Seminis",
      Description: "Hybrid Bitterground seeds weight 250 gm",
      Price: "Rs 399",
      Image: "./Product_images/se3.png",
      Warranty:"6 months",
    },
    {
      id: "004",
      Name: "VNR-212",
      Description: " High Quality Brinjal seeds weight : 240 pack of 2 ",
      Price:" Rs 329", 
      Image: "./Product_images/se4.png",
      Warranty:"No warranty",
    },
    {
      id: "005",
      Name: "VNR-145",
      Description: "F1 Hybrid Chilli Seeds",
      Price:"Rs 239", 
      Image: "./Product_images/se5.png",
      Warranty:"No warranty",
    },
    {
      id: "006",
      Name: "Known you seeds",
      Description: " F1 hybrid good quality seeds",
      Price: "Rs 340",
      Image: "./Product_images/se6.png",
      Warranty:"No warranty",
    },
    {
      id: "007",
      Name:"Sabja",
      Description: " High quality fined Basil seeds weight : 500 gm",
      Price: "Rs 249",
      Image: "./Product_images/se7.png",
      Warranty:"4 months",
    },
    {
      id: "008",
      Name: "Roasted Flax seeds ",
      Description: "For A Better You",
      Price: "Rs 249",
      Image: "./Product_images/se1.png",
      Warranty:"6 Months",
    },
  
];
