export const SeedsData= [
  {
    id: 47,
    Name: " High Quality Hybrid seeds",
    Description: " Pack of 6",
    Price: "₹ 399",
    Image: "./Product_images/se1.png",
    Warranty:"No warranty",
  },
  {
      id: 48,
      Name: "Seminis",
      Description: "High Quality Hybrid Tomato seeds",
      Price: "₹ 249",
      Image: "./Product_images/se2.png",
      Warranty:"1 year from date of manufacture",
    },
    {
      id: 49,
      Name: "Seminis",
      Description: "Hybrid Bitterground seeds weight 250 gm",
      Price: "₹ 399",
      Image: "./Product_images/se3.png",
      Warranty:"6 months",
    },
    {
      id: 40,
      Name: "VNR-212",
      Description: " High Quality Brinjal seeds weight : 240 pack of 2 ",
      Price:" ₹ 329", 
      Image: "./Product_images/se4.png",
      Warranty:"No warranty",
    },
    {
      id: 51,
      Name: "VNR-145",
      Description: "F1 Hybrid Chilli Seeds",
      Price:"₹ 239", 
      Image: "./Product_images/se5.png",
      Warranty:"No warranty",
    },
    {
      id: 52,
      Name: "Known you seeds",
      Description: " F1 hybrid good quality seeds",
      Price: "₹ 340",
      Image: "./Product_images/se6.png",
      Warranty:"No warranty",
    },
    {
      id: 53,
      Name:"Sabja",
      Description: " High quality fined Basil seeds weight : 500 gm",
      Price: "₹ 249",
      Image: "./Product_images/se7.png",
      Warranty:"4 months",
    },
    {
      id: 54,
      Name: "Roasted Flax seeds ",
      Description: "For A Better You",
      Price: "₹ 249",
      Image: "./Product_images/se1.png",
      Warranty:"6 Months",
    },
  
];
